import { Inter } from "next/font/google";
import "./globals.css";
import Sessionwrapper from "./component/Sessionwrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Sessionwrapper>
      <body className={inter.className}>{children}</body>
      </Sessionwrapper>
    </html>
  );
}
